[package]
name = "webchaussette"
version = "0.1.0"
edition = "2021"


[dependencies]
httparse = "1.8"
rand = "0.8"
base64 = "0.22"
bytes = "1.6"
sha1 = "0.10"
hex = "0.4"
tokio = { version = "1.37", features = ["full"] }